### ISSUE TITLE
Change UML - Player.java, Enemy.java, WeaponItem.java, PlayerCharacter.java, Item.java, ArmorItem.java

### ISSUE THREAD

**Issue by manuelrdsg** [avleze/TextAdventures#14]
Hey! Since the last code update I think that some additions have to be done in the _"Classes Diagram"_. This is the list with the changes to do:

1. Add **Type** atribute and **Types** constants to _Enemy.java_ and _WeaponItem.java_

2. Add **DAMAGE_TABLE** to *Player.java*

3. Add **Attack()** method to *PlayerCharacter.java* and *Enemy.java*

4. Add **usePotion()** method to *PlayerCharacter.java*

5. Add **class TypeNotFoundException** to *WeaponItem.java*
 
6. Add **getType()** method to *WeaponItem.java*

7. Change **damage** atribute name to **baseDamage** at *Player.java*

8. Add **id** param to *Player.java* constructor

9. Add **hasWeapon()** and **getId()** methods to *Player.java*

10. Delete **Item()** method in *Item.java*

11. Change **recoveryPoints** atribute name to **pointstoHealth** in *RecoveryItem.java*

12. Add **ArmorItem** class to *"Item childs"*. With ** int DefensePoints** as an atribute and **int getArmor()** as a method.

Thank you!

**Comment by avleze** [comment]
I think both variable and function names should be in lower CamelCase notation and Classes should follow upper CamelCase notation in order to follow Java style guidelines.

As Oracle Java style guidelines establishes here:

http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html#367

The names of variables declared class constants and of ANSI constants should be all uppercase with words separated by underscores ("_").

**Methods** should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

Except for variables, all instance, class, and class constants are in mixed case _with a lowercase first letter. Internal words start with capital letters._ Variable names should not start with underscore _ or dollar sign $ characters, even though both are allowed.

It is very important to have an homogeneus style, so please @manuelrdsg @luisrozo @juanrodicio follow the rules aforesaid.

About the points @manuelrdsg wrote above I need to ask some questions:

3. Which is the returning type of the method **attack()**? Is there any change?
4. Which is the returning type of the method **usePotion()**?

Thank you.

**Comment by manuelrdsg** [comment]
In both methods the returning type is boolean (or bool in C++ :P)
